services:
  backend:
    container_name: cs_curriculum_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    networks:
      - backend
      - frontend
    environment:
      - DB_NAME=cs_curriculum
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=3306
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ENDPOINT=cs_curriculum_minio:9000
      - MINIO_BUCKET=cs-curriculum
      - EMAIL_HOST_USER=giftmeonetime@gmail.com
      - EMAIL_HOST_PASSWORD=tcgwpqheiqzzhmyn

  frontend:
    container_name: cs_curriculum_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  minio:
    container_name: cs_curriculum_minio
    image: minio/minio
    env_file:
      - .env.example
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend

  db:
    container_name: cs_curriculum
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cs_curriculum
    ports:
      - "3306:3306"
    volumes:
      - csc_db_data:/var/lib/mysql
    networks: 
      - backend

  phpmyadmin:
    container_name: cs_curriculum_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  csc_db_data:
  minio_data: